stages:
  - build

build:
  stage: build
  image: node:20.17.0
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm build
  cache:
    key:
      files:
        - pnpm-lock.yaml
      paths:
        - .pnpm-store
