logging:
  level:
    com:
      mini_ssafy_heaven:
        dao: trace
    root: info
springdoc:
  swagger-ui:
    path: /docs
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json