name: mini-ssafy-heaven-be

services:
  mysql-local:
    image: mysql:8.0
    container_name: mini-ssafy-local
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    volumes:
      - data_volume:/var/lib/mysql-local
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  mysql-test:
    image: mysql:8.0
    container_name: mini-ssafy-test
    ports:
      - ${MYSQL_TEST_PORT}:3306
    volumes:
      - data_volume:/var/lib/mysql-test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  redis-local:
    image: redis:7.2.4-alpine
    container_name: redis-local
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - data_volume:/data
      - data_volume:/usr/local/conf/redis.conf
    labels:
      - name=redis
      - mode=standalone
    command: redis-server /usr/local/conf/redis.conf --requirepass ${REDIS_PASSWORD}
volumes:
  data_volume: