name: 미니싸피천국 프론트엔드 배포 파이프라인
on:
  push:
    path-ignore:
      - be/**
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    defaults:
          run:
            working-directory: ./fe

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4        

      - name: pnpm 다운로드
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: AWS Credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Node.js ${{ matrix.node-version }} 사용
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build Env 생성
        run: |
          touch ./.env
          echo "${{ secrets.FRONT_DEV_ENV }}" > ./.env

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy # S3에 배포하기
        run: aws s3 sync ./build s3://dev.mini-ssafy-heaven.com --delete